### ISSUE TITLE
Wrong (unrelated) search result!

### ISSUE THREAD

**Issue by ngekoding** [afzalsayed96/vscode-icones#10]
Just trying to find an icon in Material Design Icons with a keyword `user`, but it showing unrelated results.
And I try to compare it with MDI Explorer and from the site https://materialdesignicons.com which get a better results.

Here is the screenshots.

<img width="1280" alt="MDI Explorer & Icones" src="https://user-images.githubusercontent.com/11625690/137412826-6ed22c92-bde7-4428-938c-1cad79d0dcaf.png">

<img width="1280" alt="From https://materialdesignicons.com" src="https://user-images.githubusercontent.com/11625690/137412841-346d855f-3378-429f-a4ce-e2bbe0b89a6e.png">

**Comment by afzalsayed96** [comment]
should be raised on https://github.com/antfu/icones/issues
