### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by davay42** [afzalsayed96/vscode-icones#7]
I don't know when did it stop working, but now I see only `Not found` when loading the extension page. Reinstalling the extension doesn't help. How can I debug it to find the cause?

**Comment by afzalsayed96** [comment]
Thank you for raising this. Looking into it right away.

**Comment by afzalsayed96** [comment]
Just published a fix in `v0.0.8`. It should appear in some time on the marketplace.
Once again thanks for reporting this.
Cheers!

**Comment by davay42** [comment]
Thank you for the fast fix! The extension has updated automatically and now works fine. ✌️
