### ISSUE TITLE
After installing in vscode, it doesn't work.

### ISSUE THREAD

**Issue by hooray** [afzalsayed96/vscode-icones#9]
After installing in vscode, it doesn't work. After selecting any icon set, it keeps showing loading, and there is an error in the console.

![image](https://user-images.githubusercontent.com/1574903/136643311-0bdd0330-b007-4f24-ab8a-f188332136dd.png)

![image](https://user-images.githubusercontent.com/1574903/136643268-b43d2960-855b-400e-bc74-baeeb921d997.png)

**Comment by hooray** [comment]
the vscode version is latest

**Comment by afzalsayed96** [comment]
Microsoft keeps on breaking webview extensions with new releases. Honestly, it's really annoying.

Anyway I have published a new version on [vscode marketplace](https://marketplace.visualstudio.com/items?itemName=afzalsayed96.icones). Please re-download/update the extension to the latest version.

Thanks for bringing this up.
